project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: swift-paperless/Localization/*.xcstrings
    translation: swift-paperless/Localization/%original_file_name%
    multilingual: true
