site_name: Swift Paperless
site_url: https://swift-paperless.gessinger.dev

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme)"

    # Palette for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default

    # Palette for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate


repo_url: https://github.com/paulgessinger/swift-paperless

plugins:
  - privacy
  - exclude:
      glob:
        - "requirements.*"
  - literate-nav
  - redirects:
      redirect_maps:
        "common-issues/forbidden.md": "common_issues/forbidden.md"
        "common-issues/invalid-certificate.md": "common_issues/certificates.md"
        "common_issues/invalid-certificate.md": "common_issues/certificates.md"

        # @TODO: Enable when v1.8.0 is live
        # "common_issues/forbidden.md": "common_issues/permissions.md"
        # "common-issues/forbidden.md": "common_issues/permissions.md"

        "common-issues/local-network-denied.md": "common_issues/local-network-denied.md"


        # @TODO: Enable when v1.8.0 is live
        "common_issues/insufficient-permissions.md": "common_issues/forbidden.md"

markdown_extensions:
  - pymdownx.snippets:
  - attr_list
  - admonition

extra_css:
  - extra.css

nav:
  - index.md
  - Release notes: release_notes/
  - Common Issues:
      # @TODO: Remove when v1.8.0 is live
      - common_issues/forbidden.md

      # @TODO: Make separate page when https://github.com/paulgessinger/swift-paperless/pull/200 lands in App Store release
      # - common_issues/insufficient-permissions.md
      - common_issues/local-network-denied.md
      - common_issues/certificates.md
      - common_issues/supported-versions.md
  - privacy.md
  - libraries.md
