site_name: Swift Paperless
site_url: https://paulgessinger.github.io/swift-paperless/


theme: material

repo_url: https://github.com/paulgessinger/swift-paperless

plugins:
  - privacy

markdown_extensions:
  - pymdownx.snippets:

extra_css:
  - extra.css
