site_name: Swift Paperless
site_url: https://swift-paperless.gessinger.dev

theme:
  name: material

repo_url: https://github.com/paulgessinger/swift-paperless

plugins:
  - privacy
  - exclude:
      glob:
        - "requirements.*"
  - literate-nav
  - redirects:
      redirect_maps:
        "common-issues/forbidden.md": "common_issues/forbidden.md"
        "common-issues/invalid-certificate.md": "common_issues/invalid-certificate.md"
        "common-issues/local-network-denied.md": "common_issues/local-network-denied.md"

markdown_extensions:
  - pymdownx.snippets:

extra_css:
  - extra.css

nav:
  - index.md
  - Release notes: release_notes/
  - Common Issues: common_issues/
  - privacy.md
  - libraries.md
