name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
 - id: app_version
   type: input
   attributes:
     label: App version
     description: The version of the app you are using.
     placeholder: 1.x.x
   validations:
     required: true

 - id: backend_version
   type: input
   attributes:
     label: Paperless-ngx backend version
     description: The version of the app you are using.
     placeholder: 2.x.x
   validations:
     required: true

 - type: textarea
   id: bug-description
   attributes:
     label: Description
     description: A description of what the behavior is as opposed to the expected behavior.
   validations:
     required: true
