name: Crowdin Action

on:
  workflow_dispatch:
  schedule:
    - cron: '2 */12 * * *'
  push:
    paths: [
      'swift-paperless/Localization/*.xcstrings',
    ]
    branches: [ main ]

permissions:
  contents: write

jobs:
  synchronize-with-crowdin:
    name: Crowdin Sync
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: crowdin action
      uses: crowdin/github-action@v2
      with:
        upload_translations: false
        download_translations: true
        localization_branch_name: l10n
        pull_request_labels: 'translation'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
